# Generated by Django 5.2.12 on 2026-03-30 13:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_evento', models.DateTimeField()),
                ('categoria', models.CharField(choices=[('EMPR', 'Empreendedorismo'), ('ESPO', 'Esporte'), ('MUSI', 'Música'), ('CULT', 'Cultura')], default='CULT', max_length=4)),
                ('is_beneficente', models.BooleanField(default=False)),
                ('link_externo', models.URLField(max_length=500)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
