# Generated by Django 5.2.12 on 2026-04-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nome_local',
            field=models.CharField(default='Local não informado', help_text='Nome legível do lugar', max_length=255, verbose_name='Nome do Local (Ex: Teatro, Praça X)'),
            preserve_default=False,
        ),
    ]
