# Generated by Django 5.2.12 on 2026-04-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_nome_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pendente (Análise)'), ('PUBL', 'Publicado'), ('REJE', 'Rejeitado')], default='PEND', max_length=4, verbose_name='Status de Moderação'),
        ),
    ]
