# Generated by Django 5.2.12 on 2026-05-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Término'),
        ),
    ]
