# Generated by Django 5.2.12 on 2026-04-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nome_local',
            field=models.CharField(help_text='Ex: Teatro, Praça X', max_length=255, verbose_name='Nome do Local'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10),
        ),
    ]
