# Generated by Django 5.2.12 on 2026-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pendente (Análise)'), ('PUBL', 'Publicado'), ('REJE', 'Rejeitado'), ('ARQU', 'Arquivado (Passado)')], default='PEND', max_length=4, verbose_name='Status de Moderação'),
        ),
    ]
