# Generated by Django 5.2.12 on 2026-05-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_evento_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas_eventos/'),
        ),
    ]
